version: "3.7"

services:
  mongodb:
    container_name: mongodb
    image: localhost:5000/mongo-database:latest
    restart: always
    networks:
      - example
    ports:
      - 27017:27017

  react-front-end:
    container_name: react-front-end
    image: localhost:5000/react-front-end-dev:latest
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - example
    ports:
      - 3000:3000
    volumes:
      - '/Users/jordanheath/Development/Java/Examples/full-stack-reactive-demo/react-front-end:/app'
      - '/Users/jordanheath/Development/Java/Examples/full-stack-reactive-demo/react-front-end/node_modules:/app/node_modules'

  webflux-back-end:
    container_name: webflux-back-end
    image: localhost:5000/webflux-back-end:latest
    networks:
      - example
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  example: