# Default configuration stuff
application:
  allowed-origins:
    - "*"
server:
  port: 8080
  shutdown: graceful

---
# Docker-specific configuration - basically just addressing for the docker-compose.yml
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      database: test
      uri: mongodb://username:password@mongodb:27017/?authSource=admin